import jsPDF from "jspdf"
import "jspdf-autotable"

export const generateBloodAnalysisPDF = (data: any) => {
  const doc = new jsPDF()

  // Title
  doc.setFontSize(20)
  doc.setTextColor(40, 116, 166) // Blue color
  doc.text("Blood Analysis Report", 14, 22)

  // Date
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30)

  let yPos = 40

  // Helper to add section
  const addSection = (title: string, content: string[] | string) => {
    // Check if new page is needed
    if (yPos > 270) {
      doc.addPage()
      yPos = 20
    }

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text(title, 14, yPos)
    yPos += 8

    doc.setFontSize(11)
    doc.setTextColor(50)
    
    if (Array.isArray(content)) {
      if (content.length === 0) {
        doc.text("None detected", 14, yPos)
        yPos += 8
      } else {
        content.forEach((item) => {
            // Handle long text wrapping
            const splitText = doc.splitTextToSize(`• ${item}`, 180)
            // Check page break for each item
            if (yPos + splitText.length * 5 > 280) {
                doc.addPage()
                yPos = 20
            }
            doc.text(splitText, 14, yPos)
            yPos += splitText.length * 5 + 2
        })
      }
    } else {
        const text = content || "No information available."
        const splitText = doc.splitTextToSize(text, 180)
        doc.text(splitText, 14, yPos)
        yPos += splitText.length * 5 + 4
    }
    
    yPos += 4 // Spacing between sections
  }

  // Irregularities
  addSection("Irregularities / Abnormalities", data.irregularities)

  // Possible Diseases
  addSection("Possible Diseases / Conditions", data.possible_diseases)

  // Summary
  addSection("Summary", data.irregularity_info)

  // Causes / Risk Factors
  addSection("Causes / Risk Factors", data.causes_or_risk_factors)

  // Precautions
  addSection("Precautions & Prevention", data.precautions_and_prevention)

  // When to See a Doctor
  addSection("When to See a Doctor", data.when_to_see_a_doctor)

  // Footer disclaimer
  const pageCount = doc.getNumberOfPages()
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text("Disclaimer: This report is generated by AI and is for informational purposes only. Consult a doctor for medical advice.", 14, 290)
    doc.text(`Page ${i} of ${pageCount}`, 190, 290, { align: 'right' })
  }

  doc.save(`blood-analysis-report-${new Date().toISOString().split('T')[0]}.pdf`)
}

export const generateSymptomCheckerPDF = (data: any) => {
  const doc = new jsPDF()
  let yPos = 40

  // Title
  doc.setFontSize(20)
  doc.setTextColor(40, 116, 166) // Blue color
  doc.text("Symptom Analysis Report", 14, 22)

  // Date
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30)

  // Helper to add section
  const addSection = (title: string, content: string[] | string) => {
    if (yPos > 270) {
      doc.addPage()
      yPos = 20
    }

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text(title, 14, yPos)
    yPos += 8

    doc.setFontSize(11)
    doc.setTextColor(50)
    
    if (Array.isArray(content)) {
      if (content.length === 0) {
        doc.text("None detected", 14, yPos)
        yPos += 8
      } else {
        content.forEach((item) => {
            const splitText = doc.splitTextToSize(`• ${item}`, 180)
            if (yPos + splitText.length * 5 > 280) {
                doc.addPage()
                yPos = 20
            }
            doc.text(splitText, 14, yPos)
            yPos += splitText.length * 5 + 2
        })
      }
    } else {
        const text = content || "No information available."
        const splitText = doc.splitTextToSize(text, 180)
        doc.text(splitText, 14, yPos)
        yPos += splitText.length * 5 + 4
    }
    
    yPos += 4
  }

  // Primary Prediction
  if (data.primary_prediction) {
    addSection("Primary Prediction", `${data.primary_prediction} (Confidence: ${data.confidence}%)`)
  }

  // Symptoms
  if (data.symptoms && data.symptoms.length > 0) {
    addSection("Reported Symptoms", data.symptoms)
  }

  // Disease Info (if available)
  if (data.disease_info) {
    if (data.disease_info.common_symptoms) {
      addSection("Common Symptoms of Condition", data.disease_info.common_symptoms)
    }
    if (data.disease_info.common_causes_or_risk_factors) {
      addSection("Causes / Risk Factors", data.disease_info.common_causes_or_risk_factors)
    }
    if (data.disease_info.precautions_and_prevention) {
      addSection("Precautions & Prevention", data.disease_info.precautions_and_prevention)
    }
    if (data.disease_info.when_to_see_a_doctor) {
      addSection("When to See a Doctor", data.disease_info.when_to_see_a_doctor)
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text("Disclaimer: This report is generated by AI and is for informational purposes only. Consult a doctor for medical advice.", 14, 290)
    doc.text(`Page ${i} of ${pageCount}`, 190, 290, { align: 'right' })
  }

  doc.save(`symptom-report-${new Date().toISOString().split('T')[0]}.pdf`)
}

export const generateXRayPDF = (data: any) => {
  const doc = new jsPDF()
  let yPos = 40

  // Title
  doc.setFontSize(20)
  doc.setTextColor(40, 116, 166) // Blue color
  doc.text("X-Ray Analysis Report", 14, 22)

  // Date
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30)

  // Helper to add section
  const addSection = (title: string, content: string[] | string) => {
    if (yPos > 270) {
      doc.addPage()
      yPos = 20
    }

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text(title, 14, yPos)
    yPos += 8

    doc.setFontSize(11)
    doc.setTextColor(50)
    
    if (Array.isArray(content)) {
      if (content.length === 0) {
        doc.text("None detected", 14, yPos)
        yPos += 8
      } else {
        content.forEach((item) => {
            const splitText = doc.splitTextToSize(`• ${item}`, 180)
            if (yPos + splitText.length * 5 > 280) {
                doc.addPage()
                yPos = 20
            }
            doc.text(splitText, 14, yPos)
            yPos += splitText.length * 5 + 2
        })
      }
    } else {
        const text = content || "No information available."
        const splitText = doc.splitTextToSize(text, 180)
        doc.text(splitText, 14, yPos)
        yPos += splitText.length * 5 + 4
    }
    
    yPos += 4
  }

  // Study Type
  addSection("Study Type", data.study_type)

  // Summary
  addSection("Summary", data.summary)

  // Key Findings
  addSection("Key Findings", data.key_findings)

  // Likely Conditions
  addSection("Likely Conditions", data.likely_conditions)

  // Top Finding Details (if available from Gemini)
  if (data.top_finding && data.top_finding.details) {
    const details = data.top_finding.details
    addSection(`Detailed Information: ${data.top_finding.name} (${data.top_finding.probability})`, details.short_description)
    
    if (details.common_symptoms) {
      addSection("Common Symptoms", details.common_symptoms)
    }
    if (details.common_causes_or_risk_factors) {
      addSection("Common Causes / Risk Factors", details.common_causes_or_risk_factors)
    }
    if (details.precautions_and_prevention) {
      addSection("Precautions & Prevention", details.precautions_and_prevention)
    }
    if (details.when_to_see_a_doctor) {
      addSection("When to See a Doctor", details.when_to_see_a_doctor)
    }
    if (details.confidence) {
      addSection("AI Information Confidence", details.confidence)
    }
  }

  // Other Possibilities
  if (data.other_possibilities && data.other_possibilities.length > 0) {
    addSection("Other Possibilities (>20%)", data.other_possibilities)
  }

  // Recommendations
  addSection("Recommendations", data.recommendations)

  // Urgency
  if (data.urgency) {
    addSection("Urgency Level", data.urgency)
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text("Disclaimer: This report is generated by AI and is for informational purposes only. Consult a doctor for medical advice.", 14, 290)
    doc.text(`Page ${i} of ${pageCount}`, 190, 290, { align: 'right' })
  }

  doc.save(`xray-report-${new Date().toISOString().split('T')[0]}.pdf`)
}
